using HarmonyLib;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.GauntletUI.BaseTypes;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.GauntletUI;

namespace FullScreenCinematics.Patches
{
    internal class FullScreenCinematics
    {
        [HarmonyPatch(typeof(SceneNotification__TaleWorlds_Core_ViewModelCollection_Information_SceneNotificationVM), nameof(SceneNotification__TaleWorlds_Core_ViewModelCollection_Information_SceneNotificationVM.SetAttributes))]
        internal class CinematicsFullScreen
        {
            [HarmonyPostfix]
            static void Postfix(ref SceneNotification__TaleWorlds_Core_ViewModelCollection_Information_SceneNotificationVM __instance, ref ButtonWidget ____widget_0_2_0_4_0, ref ButtonWidget ____widget_0_2_0_4_1, ref SceneWidget ____widget_0_2_0)
            {
                //base VM widget, adapted to resolution
                Vec2 res = MBWindowManager.GetScreenResolution();
                float ratio = res.X / res.Y;
                float UIscale = ManagedOptions.GetConfig(ManagedOptions.ManagedOptionsType.UIScale) + 0.25f;
                ____widget_0_2_0.SuggestedHeight = res.Y / UIscale;
                ____widget_0_2_0.SuggestedWidth = res.X / UIscale;

                //Code to restore Executions buttons, not working yet
                //cancel
                ____widget_0_2_0_4_0.MarginLeft = 20f;
                ____widget_0_2_0_4_0.MarginRight = 20f;
                ____widget_0_2_0_4_0.MarginBottom = 20f;
                ____widget_0_2_0_4_0.MarginTop = 20f;
                ____widget_0_2_0_4_0.VerticalAlignment = VerticalAlignment.Bottom;
                ____widget_0_2_0_4_0.HorizontalAlignment = HorizontalAlignment.Left;
                ____widget_0_2_0_4_0.PositionXOffset = 20f;
                ____widget_0_2_0_4_0.PositionYOffset = 50f;
                //continue
                ____widget_0_2_0_4_1.MarginLeft = 20f;
                ____widget_0_2_0_4_1.MarginRight = 20f;
                ____widget_0_2_0_4_1.MarginBottom = 20f;
                ____widget_0_2_0_4_1.MarginTop = 20f;
                ____widget_0_2_0_4_1.VerticalAlignment = VerticalAlignment.Bottom;
                ____widget_0_2_0_4_1.HorizontalAlignment = HorizontalAlignment.Left;
                ____widget_0_2_0_4_1.PositionXOffset = res.X - 300f;
                ____widget_0_2_0_4_1.PositionYOffset = 50f;
            }
        }
    }
}
